server:
  port: 10087

spring:
  application:
    name: music
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://127.0.0.1:3306/songjoyhub?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 15 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 25 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
  data:
    redis:
      password: l1234567890
      host: 106.52.57.96
      port: 6379
  servlet:
    multipart:
          max-file-size: 10MB  # 设置最大文件大小
          max-request-size: 10MB  # 设置最大请求大小
# cos存储


#rocketmq:
#  name-server: 106.52.57.96:9876
#  producer:
#    group: lx-song_joy_hub_music_pg
#    send-message-timeout: 2000
#    retry-times-when-send-failed: 1
#    retry-times-when-send-async-failed: 1